### ISSUE TITLE
`FieldAccessException` when trying to access publicized fields.

### ISSUE THREAD

**Issue by ameisen** [krafs/Publicizer#12]
Whenever a publicized field is accessed, I am getting a `FieldAccessException`. I have not yet tested it, but I expect that _all_ accesses will likely result in access exceptions.

An example:

```
	private unsafe void Construct<T>(
		ReadOnlyPinnedSpan<T>.FixedSpan dataIn,
		Vector2I size,
		bool mipmap,
		SurfaceFormat format,
		SurfaceType type,
		bool shared
	) where T : unmanaged {
		glTarget = TextureTarget.Texture2D; // Exception happens here
		format.GetGLFormat(GraphicsDevice, out glInternalFormat, out glFormat, out glType);
		...
	}
```

the code in MonoGame looks like this:

```
namespace Microsoft.Xna.Framework.Graphics
{
    public abstract partial class Texture
    {
        internal int glTexture = -1;
        internal TextureTarget glTarget;
        ...
    }
}
```

This is what my project file looks like: [SpriteMaster.csproj](https://github.com/ameisen/SV-SpriteMaster/blob/5bee008c0051eff6059a103b853f255a0ea1eef6/SpriteMaster/SpriteMaster.csproj)

And this is the properties file it imports: [SpriteMasterCommon.props](https://github.com/ameisen/SV-SpriteMaster/blob/5bee008c0051eff6059a103b853f255a0ea1eef6/SpriteMasterCommon.props)

And all assembly attributes and such are here: [Assembly.cs](https://github.com/ameisen/SV-SpriteMaster/blob/5bee008c0051eff6059a103b853f255a0ea1eef6/SpriteMaster/Assembly.cs) (I should note that removing the security-related attributes changes nothing)

The only unusual thing is that the game (this is a Stardew Valley mod) is loaded through [SMAPI](https://github.com/Pathoschild/SMAPI), and runs on .NET 5. Mod assemblies are imported dynamically by SMAPI.

**Comment by krafs** [comment]
Thanks for an exemplary ticket. Couldn't ask for more details :) 

The **FieldAccessException** should have been suppressed by Publicizer setting AllowUnsafeBlocks = true behind the scenes in your project. I see you do that explicitly too.
However, it turns out this only works when the application runs in the Mono runtime (see #13).

Basically: Mono + AllowUnsafeBlocks + accessing publicized member = OK

In your case, Monogame is using .NET5, and using the CoreCLR runtime, which doesn't seem to work.

Unfortunately, I don't know if there is a way to do the same thing in other runtimes than Mono. This means that you probably won't be able to use Publicizer for your use case.

I'll make sure to add a disclaimer about this in the Readme.

**Comment by ameisen** [comment]
I found another NuGet library that works for my use case: [IgnoresAccessChecksToGenerator](https://github.com/aelij/IgnoresAccessChecksToGenerator).

I believe that it largely does the same thing as yours, but _also_ emits `IgnoresAccessChecksToAttribute` (which the .NET runtime does recognize, but the C# compiler does _not_).

[You can see their implementation here.](https://github.com/aelij/IgnoresAccessChecksToGenerator/blob/main/src/IgnoresAccessChecksToGenerator.Tasks/PublicizeInternals.cs)

I'd still _prefer_ to use yours, since it's more flexible. It should be plausible to adopt similar functionality.

**Comment by krafs** [comment]
I remember seeing that project before. It's remarkable how similar some code segments are to this.
I would imagine the main difference with using Publicizer is the granularity with which you can specify members, instead of blanket-selecting all members in an assembly. The same attribute could most likely be emitted in Publicizer too, yeah.

Unfortunately I don't have the time to dig into this at the moment. I appreciate you preferring Publicizer, but if you need something functional soon, that project is probably better.

**Comment by ameisen** [comment]
Interestingly, I actually end up presently having to use *both*.

The package that adds the attribute opens up the assembly, but it doesn't actually publicize _everything_ - yours has better support for doing that.

**Comment by krafs** [comment]
Closed by #28.

**Comment by Hidend** [comment]
I'm getting FieldAccessException using Publicizer towards a .dll using .NET Framework (v4.0.30319), I'm trying to use:
`internal static bool IsSpectating;
`
And I get System.FieldAccessException, thing is that If I use it with a property that I should actually see, I also get the error:

`public static int health;
`
This last thing is actually not true at 100%, since all these properties come from a class that is internal, so any property that I access from it it will fail:
`internal class Main
`
After Publicizer is applied, I get this:
`public class Main
`
But it does indeed fail, Any ideas?

**Comment by krafs** [comment]
@Hidend We can continue this discussion in a new issue #102
