### ISSUE TITLE
[Feature request] Copy xml docs alongside publicized assembly

### ISSUE THREAD

**Issue by gotmachine** [krafs/Publicizer#15]
After publicizing an assembly, the reference is pointing at the dll in `obj\config\PublicizedAssemblies`. If there are xml docs (methods summary / param info, etc) for that assembly, the IDE won't find them anymore.

It would be nice if upon creating the publicized dll, the xml docs file was copied alongside it (and renamed accordingly).

**Comment by krafs** [comment]
This sounds like a good idea!
So, do all IDEs just look for the corresponding xml file by convention? They just look in the same directory, for a file with the same name?

**Comment by gotmachine** [comment]
> They just look in the same directory, for a file with the same name?

Visual Studio definitely does this and to my knowledge there is no other way to get it to load the xml docs for a given reference assembly (hence the request). I guess the same applies to other IDEs as well, but I can't say for sure.

**Comment by krafs** [comment]
I thought that the path to the xml file was resolved and kept as metadata in msbuild, and then read by e.g. VS. If so, we could have just overwritten that path to point to the original xml file instead of copying it. But yeah, doesn't seem like that's how it works. VS just looks in the same directory.

Anyway, copying (and renaming) any existing xml files along with the dll during publicization should be pretty straightforward.

You can submit a PR if you like. Otherwise, I'm getting some time off soon and can probably add this in.
