### ISSUE TITLE
Unable to publicize assemblies in Bannerlord.ReferenceAssemblies nuget package

### ISSUE THREAD

**Issue by XT-0xFF** [krafs/Publicizer#53]
I've been using this without problem for publicizing RimWorld assemblies, but when trying to use it for Mount & Blade 2: Bannerlord it doesn't seem to work. 
(I'm probably doing something wrong.)

For example I was trying to access the setter to HeroDeveloper.TotalXp (namespace: TaleWorlds.CampaignSystem.CharacterDevelopment in TaleWorlds.CampaignSystem.dll), which is private. Intending to have it accessible, I added the assembly to be publicized, yet after doing so I still have no access to the private setter or private fields.

Interestingly though, the protected methods of the abstract MBSubModuleBase class (namespace: TaleWorlds.MountAndBlade.MBSubModuleBase in TaleWorlds.MountAndBlade.dll) are publicized.

My project file: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ASSEMBLYNAME</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bannerlord.ReferenceAssemblies" Version="1.0.0.4373" />
    <PackageReference Include="Krafs.Publicizer" Version="2.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Bannerlord.MCM" Version="5.0.4" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
  </ItemGroup>
  <ItemGroup>
    <Publicize Include="TaleWorlds.MountAndBlade" />
    <Publicize Include="TaleWorlds.Core" />
    <Publicize Include="TaleWorlds.CampaignSystem" />
  </ItemGroup>
</Project>
```

---

I also tried applying
```
<PropertyGroup>
    <PublicizeAll>true</PublicizeAll>
</PropertyGroup>
```
but that pretty much broke everything, highlighting everything with errors.

**Comment by krafs** [comment]
You're not doing anything wrong. This is a common issue with reference assemblies. Early versions of [Krafs.Rimworld.Ref](https://www.nuget.org/packages/Krafs.Rimworld.Ref/) suffer from the same issue.

The reason the `HeroDeveloper.TotalXp`-setter isn't publicized is because it doesn't exist in the reference assembly. The Bannerlord reference assemblies are generated by [this project](https://github.com/BUTR/Bannerlord.ReferenceAssemblies) with a tool called [Refasmer](https://github.com/JetBrains/Refasmer), the same tool used to generate [Krafs.Rimworld.Ref](https://github.com/krafs/RimRef). Refasmer, like many other reference assembly-tools, cleverly attempts to completely remove all members that aren't visible from outside the assembly. This reduces the size of the reference assembly significantly, and is normally a great feature. However, it's not very compatible with publicizers.

The Bannerlord project seems to be using Refasmer [here](https://github.com/BUTR/Bannerlord.ReferenceAssemblies/blob/f19f639ed0852bda42c2af5a991c2a411072d3cf/src/Bannerlord.ReferenceAssemblies/Tool.cs#L175). It's calling `refasmer <filepath> -o <output> -c`. Compare that with how Krafs.Rimworld.Ref uses Refasmer [here](https://github.com/krafs/RimRef/blob/30ed1e19d7a287aae01b4d0a344e87793f0edaa3/.github/workflows/make-and-upload-package.yml#L96), calling `refasmer -v --all -O <outputDir> <filepath>`. The trick is to use the `--all`-flag. That will keep all members in the reference assembly, regardless of visibility (see [Refasmer usage](https://github.com/JetBrains/Refasmer#usage)).

Unfortunately, there's nothing you can do to fix this with the existing versions of the package. I recommend that you create an issue at the [Bannerlord project](https://github.com/BUTR/Bannerlord.ReferenceAssemblies) and ask if they'd be open to adding the `--all`-flag to the refasmer call, and simply have all future package versions include non-public members. You can link to this issue for the explanation.

**Comment by XT-0xFF** [comment]
Thank you for this detailed explanation of the problem. 

I had not even thought of that, but it makes sense to keep out the normally unnecessary, non-visible parts of the assembly to keep the size down. Guess they did not know that a tool like this exists for allowing access to non-public members for easier and more efficient modding!

Definitely going to bring it up with them, thank you for the advice.
If they prefer not to change it, I will have to stick with using reflection. Would have just preferred to avoid it as much as possible.

Closing the issue as it is not related to Publicizer!
