### ISSUE TITLE
Publicizing as non-reference assemblies.

### ISSUE THREAD

**Issue by Sl4vP0weR** [krafs/Publicizer#63]
Using version 2.2.0.
`<PublicizeAsReferenceAssemblies>false</PublicizeAsReferenceAssemblies>` seems to not work.
Publicized string type in mscorlib: 
![image](https://user-images.githubusercontent.com/42337892/212855675-efb32e9f-49c7-4035-900e-640250c94fdd.png)

**Comment by krafs** [comment]
Yeah, PublicizeAsReferenceAssemblies was removed in 2.0.0. Now, they're never saved as reference assemblies. Code is always retained.

Where is that assembly located on disk? It looks like it is a reference assembly.

**Comment by Sl4vP0weR** [comment]
Looks like it's my fault, was using your Krafs.Rimworld.Ref but it's includes only reference assemblies unfortunately, is there some other work around? I still want to use your package, but with non-reference assemblies.

**Comment by krafs** [comment]
Yeah, this is one of the drawbacks of Krafs.Rimworld.Ref. The method bodies have to be stripped, otherwise we're violating the EULA by distributing Rimworld's source code. But stripping the method bodies makes IDE decompilation less useful.

I've seen some different approaches. The most common is simply accepting it, and just always keeping the real assemblies open in e.g. ILSpy alongside VS. This is my approach, but I don't do heavy modding anymore, so maybe I'm the wrong target audience :)

I've thought about maybe making some msbuild target that references the real assemblies locally if it can find them in e.g. the Steam folder. But this would only work reliably if the local assembly versions are exactly the same as the referenced nuget package. I'm not sure the end result is worth the complexity.

**Comment by Sl4vP0weR** [comment]
Thanks for reply, ok, I will try to find workaround for my template, thanks.
