### ISSUE TITLE
Publicizing members as sealed - would it cause issues?

### ISSUE THREAD

**Issue by SokyranTheDragon** [krafs/Publicizer#69]
From the readme file: `Overriding a publicized member will throw an error at runtime.`

It made me wonder - would it be possible to publicize them as sealed (if relevant) to prevent overriding them? Specifically, if this was done - would it actually work during runtime?

I've tried to search the repo (including issues), but could not find anything discussing it so I've decided to ask about it myself.

**Comment by krafs** [comment]
It's an interesting idea, for sure. I imagine it would involve some additional tweaking beyond slapping a `sealed` on all overridable members though.

For example, a class with the following member:
```cs
protected abstract string GetString();
```
Making this non-overridable would involve removing the `abstract`. And since it now isn't `abstract`, it either needs to be made `extern` (so it can exist without a method body) or be given an empty method body. It would have to be more thoroughly tested. There might be edge cases.

In the case of regular virtual members, like this:
```cs
protected virtual string GetString()
{
    // Stuff...
}
```
I tried to edit the Rimworld assembly by removing the `virtual`-keyword from `JobDriver.SetInitialPosture()`-method and it was unable to re-compile.

There's also the fact that many versions of the Mono runtime doesn't care. The statement in the readme is an overgeneralization. CoreClr definitely throws an error at runtime, but many versions of Mono won't complain as long as you compile your assembly as `unsafe`. So there'd have to be a toggle for users to say whether they want to apply `sealed` to virtual members or not.

Not sure how easy it'd be to implement in a robust way, without making the library more complex to use. The idea is good, I'm just worried the implementation might not be as straighforward.
